# Generated by Django 5.1.7 on 2025-03-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_nickname', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='', max_length=150)),
                ('user_email', models.CharField(default='', max_length=100)),
                ('user_age', models.CharField(default=0, max_length=2)),
            ],
        ),
    ]
